theme = "soho"
baseurl = "/"
languageCode = "en-uk"
title = "Roberto's website"
DefaultContentLanguage = "en-uk"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
googleAnalytics = "UA-168074535-1"

[params]
title = "Roberto's website"
author = "Roberto Villegas-Diaz"
# description = "Example Blog"
# gravatar = "soho@example.com"
images = ["images/roberto.jpg"]
profilePicture = "images/roberto.jpg"
copyright = "Roberto Villegas-Diaz"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
themeColor = "#15446f"

[permalinks]
post = "/:year/:month/:day/:slug/"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/roberthillo/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/villegar/web"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://www.twitter.com/roberthillo"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
