on:
  push:
    branches: master
  schedule:
    - cron:  '0 0-1,5-23 * * *'

name: Render trainR post

jobs:
  render:
    name: Render trainR post
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NRE: ${{ secrets.NRE }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Query dependencies
        run: |
          install.packages(c("remotes", "blogdown"))
          remotes::install_cran("rmarkdown")
          remotes::install_github("villegar/trainR", "dev")
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Render README
        run: |
          # list up Rmd files
          rmd <- list.files("content/post/2021-02-08-trainr-an-interface-to-the-national-rail-enquiries-systems", "\\.Rmd$", recursive = TRUE, full.names = TRUE)
          
          # list up md files
          md_files  <- sub("\\.Rmd$", ".md", rmd)
          names(md_files) <- Rmd_files
          knitr::knit(input = rmd[1], output = md_files[1], encoding = "UTF-8")
          # Rscript -e 'rmarkdown::render("content/post/2021-02-08-trainr-an-interface-to-the-national-rail-enquiries-systems/index.en-uk.Rmd", blogdown::html_page())'
        shell: Rscript {0}
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit content/post/2021-02-08-trainr-an-interface-to-the-national-rail-enquiries-systems/index.en-uk.html -m 'Re-build trainR post' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
